logging:
  level:
    org:
      springframework:
        web: debug
    #        security: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_DATABASE_URL}
    username: ${RDS_DATABASE_USERNAME}
    password: ${RDS_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile
          #          github:
          #            client-id: ${GITHUB_CLIENT_ID}
          #            client-secret: ${GITHUB_CLIENT_SECRET}
          #            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          #            scope: user:email, user
          #            authorization-grant-type: authorization_code
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_SECRET_KEY}
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope: email, profile
            client-name: Naver
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email

        provider:
          #          github:
          #            authorization-uri: https://github.com/login/oauth/authorize
          #            token-uri: https://github.com/login/oauth/access_token
          #            user-info-uri: https://api.github.com/user
          #            user-name-attribute: login
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 420

config:
  domain: http://mainmay.s3-website.ap-northeast-2.amazonaws.com/
